grammar.js, test/corpus/assignment.txt
Fixes errors where lines like `this.foo = bar` don't parse.
To test: use
```
npx tree-sitter test
```
The `this assignment` test should pass.
_Pad's Comment:_
> 'This is nice, and it might simplify the original grammar of Kotlin, but I'm a bit worried that we deviate now even
> more from the original grammar. Fwcd already deviated from the original grammar a little on how he is handling expressions. I'd rather see us go back to the original spec of Kotlin where there is a directly_assignable_expression,
> and a postfix_unary_operator, etc.'
=> Adding to assignment in grammar

grammar.js
Fixes the issue of the this assignment fix lowering our parsing rate; currently getting an `86.230%` parsing rate, up from the 83.5% we have without this fix 😄 
cc: @aryx
=> add a conflict for postfix suffix

grammar.js, test/corpus/classes.txt, test/corpus/expressions.txt, test/corpus/source-files.txt, test/corpus/statements.txt
Changes:
1. Added support for semicolons separating statements with no new line in between them
2. Changed `type_test` to be more similar to kotlin grammar (type instead of expression)
Currently getting 93.865% parsing rate with the multiple file annotations fix that @aryx also has. I took out the changes so that we don't have a conflict during future merges.
_To test:_
run `npx tree-sitter test`
=> Small grammar edits

binding.gyp, bindings/rust/build.rs, grammar.js, src/grammar.json, src/node-types.json, src/scanner.c, src/tree_sitter/parser.h, test/corpus/newlines.txt, test/corpus/types.txt
This imitates the Automatic Semicolon Insertions (ASI) done in
Javascript for Kotlin, to better deal with newlines that can cut
certain definitions and expressions in two.
This closes https://github.com/fwcd/tree-sitter-kotlin/issues/32
test plan:
see new newlines.txt corpus test
=> New scanner.c to better handle newlines

grammar.js, src/grammar.json, src/node-types.json, test/corpus/newlines.txt, test/corpus/soft_keywords.txt
This improves our parsing stats to 98.6% on our Kotlin corpus
test plan:
test file included
$ tree-sitter test
=> Parse getter/setter even when after a newline

grammar.js, test/corpus/classes.txt, test/corpus/functions.txt
This PR:
* adds `set` and `get` as possible simple_identifiers
* adds optional commas after parameters
I'm getting around 99.05% parsing after these changes.
_To test:_
`npx tree-sitter test`
cc: @aryx @fwcd
=> small grammer edits to get us over 99% parsing

grammar.js, src/grammar.json, src/node-types.json, test/corpus/functions.txt, test/corpus/literals.txt
As mentioned in #43, these grammar fixes are to allow for better and more expansive. querying. The only change not implemented was separating the labels from the `jump_expressions`, since an expression like `return@` causes a  conflict between `prefix_expression` and `return_expression`.
=> Minor grammar fixes

grammar.js, src/scanner.c, test/corpus/expressions.txt, test/corpus/newlines.txt, test/corpus/source-files.txt
This pull request copies `tree-sitter-javascript`'s ASI code and modifies so that it can handle single line statements such as `import foo import baz` and `if (true) foo else bar`.
Furthermore it pushes the responsibility for matching semicolons to the ASI code instead of the generated tree-sitter parser.
Closes: #45
=> Improve ASI

grammar.js, src/grammar.json, src/tree_sitter/parser.h
So for instance, we may be dealing with a case like:
```
class Foo() : Bar(
x = "hi",
y = "bye",
) {
// ...
}
```
Currently, we do not allow the trailing comma in the delegation specifiers.
=> allow trailing comma in delegation specifiers

grammar.js, src/grammar.json, src/tree_sitter/parser.h, test/corpus/types.txt
Oops. Turns out, the commit I made earlier (#61) was wrong.
I don't want the comma on the delegation specifiers, I want it on the constructors. I've added some tests to reflect this, sorry.
@fwcd
=> revert erroneous commit and add trailing comma for constructors

grammar.js, src/grammar.json, src/node-types.json, src/tree_sitter/parser.h, test/corpus/types.txt
This PR allows type parameters to occur after a type alias, which is allowed according to the Kotlin grammar:
https://kotlinlang.org/docs/reference/grammar.html#typeParameters
=> fix: add type params to typealias

grammar.js, src/grammar.json, src/node-types.json, test/corpus/annotations.txt, test/corpus/assignment.txt, test/corpus/classes.txt, test/corpus/expressions.txt, test/corpus/functions.txt, test/corpus/newlines.txt, test/corpus/soft_keywords.txt, test/corpus/source-files.txt, test/corpus/statements.txt
This PR exposes the `function_value_parameters` node. This makes it easier to write query the signature of the function like this: 
```
(
(function_declaration (simple_identifier) @name
(function_value_parameters) @paramter_list 
(function_body) @body) 
@func)
``` 
( @fwcd )
=> Expose function_value_parameters

grammar.js, src/grammar.json, src/node-types.json, test/corpus/types.txt
This PR adds in "not nullable types", which to my understanding are types that look like `T1 & T2`.
https://kotlinlang.org/docs/reference/grammar.html#definitelyNonNullableType
Our parse rate goes from 98.366% to 98.372% with this.
=> feat: add not nullable types

src/scanner.c
My previous PR at https://github.com/fwcd/tree-sitter-kotlin/pull/76 made it such that we used different logic for string scanning. I remarked that 
> Since the string internals are all hidden in the syntax tree anyways, there's no point in going to the effort of 
specifically separating the string end from string contents. If we see a bunch of quotes in a row, then we just go until
they stop appearing, then stop lexing and call it the string's end.
This is not exactly true. I was under the impression because the `tree-sitter parse` output showed just a single node for `string_literal`, that it would all be subsumed under the same thing, and it wouldn't matter exactly where you called `STRING_END` or `STRING_CONTENT`.
However, in the grammar, we see that there are indeed `string_end` and …
=> fix: don't put string contents in string end token

.gitignore, Makefile, bindings/c/tree-sitter.h.in, bindings/c/tree-sitter.pc.in
This adds a Makefile and bindings to more easily build static/dynamic libraries for use in C-based languages. The implementation is intended to be as generic as possible, to make for easier adoption and diffing.
This comes from discussion in the main tree-sitter repo https://github.com/tree-sitter/tree-sitter/issues/1488.
=> C Bindings

package.json
This section is necessary for using the grammar in tools like tree-sitter-cli, tree-sitter-graph, etc.
Someone has found this issue and made a PR #56 , but unfortunately wrote a wrong scope. This PR handled it correctly, thus you can merge this one and close #56 .
=> Add missing tree-sitter section in package.json

.github/workflows/build.yml, .github/workflows/deploy-to-github.yml
This applies the suggestion from https://github.com/fwcd/tree-sitter-kotlin/issues/98#issuecomment-1743758082 and uses emscripten 2.0.17 to generate a WASM binary. Additionally, the binary is now built and exported as part of the standard CI workflow.
=> Build WASM binary in normal build workflow

grammar.js, src/grammar.json, src/node-types.json, test/corpus/classes.txt
Value class syntax is similar to data class syntax and is described here: https://kotlinlang.org/docs/inline-classes.html.
Fixes https://github.com/fwcd/tree-sitter-kotlin/issues/102
=> Add value class support.

grammar.js, src/grammar.json, src/node-types.json, test/corpus/expressions.txt
Upon reviewing nvim-treesitter/nvim-treesitter#5527 I noticed that (a) the jump expression labels are anonymous nodes and (b) the `_this_at` and `_super_at` rules are unused. This change makes it easier to capture the labels and classes and ensures that qualified calls are parsed as expected. I wanted to use `token.immediate("@")` in all of the `*_at` rules but the `label` rule would take precedence (even after editing it and raising the other rules' precedence) so I had to compromise.
=> fix: improve jumps and class qualifiers

grammar.js, src/grammar.json, src/node-types.json, test/corpus/annotations.txt, test/corpus/assignment.txt, test/corpus/classes.txt, test/corpus/expressions.txt, test/corpus/functions.txt, test/corpus/literals.txt, test/corpus/newlines.txt, test/corpus/soft_keywords.txt, test/corpus/source-files.txt, test/corpus/statements.txt, test/corpus/types.txt
Hi,
This is a continuation of /pull/74 given Vladimir Reshetnikov said they would not be pursuing it anymore.
In [Searchfox](https://searchfox.org), we leverage tree-sitter to add some information on where symbols are found. For instance if you search for the C++ symbol [mozilla::dom::MediaControlKeySource::IsOpened](https://searchfox.org/mozilla-central/search?q=symbol:_ZNK7mozilla3dom21MediaControlKeySource8IsOpenedEv), and you find 9 results in the file `dom/mediacontrol/MediaControlKeyManager.cpp`, it's super useful to know in which function each result was found (tree-sitter is what enables those `// found in` comments). We are adding Kotlin support to Searchfox, hence this PR.
For now we only use the `name` and `body` fields of `class_definition` and `function_declaration`, but …
=> Add field names

src/scanner.c
exit is not thread-safe and abort is preferred for program termination in general
https://github.com/tree-sitter/tree-sitter/issues/805
https://github.com/tree-sitter/tree-sitter/issues/2991
Thanks!
=> fix(scanner): prefer abort over exit

src/scanner.c
- Use local import for `parser.h`
- Use the new built-in array API
- Define `DELIMITER_LENGTH` constant
- Mark simple functions as `inline`
- Remove functions that are only used once
- Remove rarely used `mark_end` function
- Simplify `scan_whitespace_and_comments` function
- Use bitwise and instead of modulo
- Various codestyle improvements
=> refactor(scanner): code cleanup

package.json
This migrates the deprecated `tree-sitter build-wasm` script to `tree-sitter build --wasm`. It also adds a `start` script that automatically builds the Wasm binary before launching the playground for convenience.
=> Update `build-wasm` script and add start script

grammar.js, src/grammar.json, src/node-types.json, src/tree_sitter/array.h, src/tree_sitter/parser.h, test/corpus/source-files.txt
Parse "." and "*" for wildcard imports as separate nodes, allowing them to be more precisely highlighted.
Create a new named node `wildcard_import`.
=> feat(grammar): Expose wildcard imports as named nodes

grammar.js, src/grammar.json, src/node-types.json, src/tree_sitter/array.h, src/tree_sitter/parser.h, test/corpus/assignment.txt, test/corpus/classes.txt, test/corpus/expressions.txt, test/corpus/literals.txt, test/corpus/newlines.txt, test/corpus/source-files.txt, test/corpus/types.txt
Expose string_content to the parse tree so that we don't need to manually strip quotes to get the string content.
=> Expose string-content

src/scanner.c
https://github.com/fwcd/tree-sitter-kotlin/pull/115 introduces a segfault in the following function in `scanner.c`. I noticed 
`(signal: 11, SIGSEGV: invalid memory reference` in some of our tests after upgrading.
```
void tree_sitter_kotlin_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {
Stack *stack = (Stack *)payload;
if (length > 0) {
memcpy(stack->contents, buffer, length); // <<< stack.contents can be null
stack->size = length;
} else {
array_clear(stack);
}
}
```
This PR fixes the segfault by adding a null check here.
=> Fix seg fault in scanner.c: Allocate the stack array if null

grammar.js, src/grammar.json, src/node-types.json, test/corpus/expressions.txt, test/corpus/newlines.txt
Currently, it is rather cumbersome to detect the 'else' part of an 'if-else' construct in the parse tree because the 'else' part is flattened. This PR makes the parse tree more explicit by fields for the if-else-parts. This makes the grammar more robust and in line with other grammars like Java.
=> Make the 'else' part explicit in parse trees

src/scanner.c
memcpy(dst, src, size) is a Undefined behavior if src is nullptr, even if size is 0. (https://en.cppreference.com/w/c/string/byte/memcpy)
I ran into a case where the input Stack parameter for the scanner serialize call has the has NULL content, 0 size and 0 capacity. And that caused runtime crash when build with UBSAN.
I thought about checking src being nullptr instead of size being 0. But I think if we ever get an input where src is nullptr but size > 0, that's bug somewhere else and we should crash program to surface that. Nullptr + zero size sounds relatively legit to actually hit this function, we just shouldn't try to do memcpy with such empty src. Thus i went with checking the size, not the src ptr. Let me know if people prefer other way. Thanks.
=> Do not memcpy from empty source

README.md, grammar.js, src/grammar.json, src/node-types.json, src/tree_sitter/parser.h, test/corpus/annotations.txt, test/corpus/expressions.txt, test/corpus/statements.txt, test/corpus/types.txt
Fixes https://github.com/fwcd/tree-sitter-kotlin/issues/153 by using receiver_type.
- I'm not too familiar with grammar-writing, so I'm unsure if my fixes here are ideal.
- `function_type` has been updated to more closely match the [official grammar for functionType](https://kotlinlang.org/spec/syntax-and-grammar.html#grammar-rule-functionType). 
- `[$.receiver_type], [$.receiver_type, $._type],` have been added to the conflicts list. Adding these conflict entries made previously error-generating Kotlin inputs non-error-generating with sensible parse trees. It's unclear if this is the best strategy for specifying the grammar.
Draft mode because this also includes changes from https://github.com/fwcd/tree-sitter-kotlin/pull/152.
=> Improve handling of receiver types

grammar.js, src/grammar.json, src/node-types.json, src/tree_sitter/parser.h, test/corpus/assignment.txt
Currently, we cannot parse programs which have things like:
```kotlin
Foo(context).elem = var1
```
which assigns `var1` to the property `elem` of the object returned by `Foo(context)`. You can see in the Kotlin playground that such code parses, and is attempted to evaluate:
https://pl.kotl.in/E1IajnqkH
This PR just moves `call_expression` so it may appear in an `assignment` LHS.
=> fix: allow call expressions in assignment

src/scanner.c, test/corpus/expressions.txt
The original bug was that a function applied using the infix syntax such as `a eq b`. This would produce a parse error if the operator started with the letter `e` but not other letters. This was a problem in the scanner code for automatic semicolons. I also found a problem with infix operators starting with `import` as in `a import_ b`. This is also fixed now.
=> Fix parsing errors for infix expressions

Cargo.lock, Cargo.toml, bindings/rust/README.md
=> Update tree-sitter crate dependency to >=0.21

grammar.js, src/grammar.json, test/corpus/types.txt
Supporting trailing commas in type-params and type-arguments to handle cases like:
```kotlin
typealias Foo = 
SomeTypeWithParams<
Int, 
Int,
>
```
I've added a single test, but feel free to let me know if there should be more.
=> Type params with trailing commas
